URLS = [
    {:name=>"Miami", :url=>"https://www.indeed.com/jobs?q=%2435%2C000&l=Miami%2C+FL&vjk=47ad6f146bdb38b6"},
    {:name=>"Tampa", :url=>"https://www.indeed.com/jobs?q=%2435%2C000&l=Tampa%2C+FL&vjk=755069ad4d1b55f3"},
    {:name=>"Orlando", :url=>"https://www.indeed.com/jobs?q=%2435%2C000&l=Orlando%2C+FL&vjk=be54d60a945f387a"},
    {:name=>"St. Petersburg", :url=>"https://www.indeed.com/jobs?q=%2435%2C000&l=St.+Petersburg%2C+FL&vjk=a2798dfd6b44cbca"},
    {:name=>"Hialeah", :url=>"https://www.indeed.com/jobs?q=%2435%2C000&l=Hialeah%2C+FL&vjk=1f6688f53ad7f71e"},
    {:name=>"Port St. Lucie", :url=>"https://www.indeed.com/jobs?q=%2435%2C000&l=Port+St.+Lucie&vjk=1ebd75596f27b357"},
    {:name=>"Cape Coral", :url=>"https://www.indeed.com/jobs?q=%2435%2C000&l=Cape+Coral%2C+FL&vjk=389dea8e44eef9c2"},
    {:name=>"Tallahassee", :url=>"https://www.indeed.com/jobs?q=%2435%2C000&l=Tallahassee%2C+FL&vjk=ef96454e754e9ae0"},
    {:name=>"Fort Lauderdale", :url=>"https://www.indeed.com/jobs?q=%2435%2C000&l=Fort+Lauderdale%2C+FL&vjk=34f20be641c0fecb"},
    {:name=>"Pembroke Pines", :url=>"https://www.indeed.com/q-$40,000-l-Pembroke-Pines,-FL-jobs.html?vjk=95e9e4928ae14fd8"},
    {:name=>"Hollywood", :url=>"https://www.indeed.com/q-$40,000-l-Hollywood,-FL-jobs.html"},
    {:name=>"Miramar", :url=>"https://www.indeed.com/q-$40,000-l-Miramar,-FL-jobs.html"},
    {:name=>"Coral Springs", :url=>"https://www.indeed.com/q-$40,000-l-Coral-Springs,-FL-jobs.html"},
    {:name=>"Gainesville", :url=>"https://www.indeed.com/q-$40,000-l-Gainesville,-FL-jobs.html"},
    {:name=>"Lehigh Acres", :url=>"https://www.indeed.com/q-$40,000-l-Lehigh-Acres,-FL-jobs.html"},
    {:name=>"Clearwater", :url=>"https://www.indeed.com/q-$40,000-l-Clearwater,-FL-jobs.html"},
    {:name=>"Palm Bay", :url=>"https://www.indeed.com/q-$40,000-l-Palm-Bay,-FL-jobs.html"},
    {:name=>"Brandon", :url=>"https://www.indeed.com/q-$40,000-l-Brandon,-FL-jobs.html"},
    {:name=>"West Palm Beach", :url=>"https://www.indeed.com/q-$40,000-l-West-Palm-Beach,-FL-jobs.html"},
    {:name=>"Lakeland", :url=>"https://www.indeed.com/q-$40,000-l-Lakeland,-FL-jobs.html"},
    {:name=>"Pompano Beach", :url=>"https://www.indeed.com/q-$40,000-l-Pompano-Beach,-FL-jobs.html"},
    {:name=>"Miami Gardens", :url=>"https://www.indeed.com/q-$40,000-l-Miami-Gardens,-FL-jobs.html"},
    {:name=>"Spring Hill", :url=>"https://www.indeed.com/q-$40,000-l-Spring-Hill,-FL-jobs.html"},
    {:name=>"Davie", :url=>"https://www.indeed.com/q-$40,000-l-Davie,-FL-jobs.html"},
    {:name=>"Boca Raton", :url=>"https://www.indeed.com/q-$40,000-l-Boca-Raton,-FL-jobs.html"},
    {:name=>"Riverview", :url=>"https://www.indeed.com/q-$40,000-l-Riverview,-FL-jobs.html"},
    {:name=>"Sunrise", :url=>"https://www.indeed.com/q-$40,000-l-Sunrise,-FL-jobs.html"},
    {:name=>"Plantation", :url=>"https://www.indeed.com/q-$40,000-l-Plantation,-FL-jobs.html"},
    {:name=>"Deltona", :url=>"https://www.indeed.com/q-$40,000-l-Deltona,-FL-jobs.html"},
    {:name=>"Miami Beach", :url=>"https://www.indeed.com/q-$40,000-l-Miami-Beach,-FL-jobs.html"},
    {:name=>"Palm Coast", :url=>"https://www.indeed.com/q-$40,000-l-Palm-Coast,-FL-jobs.html"},
    {:name=>"Alafaya", :url=>"https://www.indeed.com/q-$40,000-l-Alafaya,-FL-jobs.html"},
    {:name=>"Fort Myers", :url=>"https://www.indeed.com/q-$40,000-l-Fort-Myers,-FL-jobs.html"},
    {:name=>"Town 'n' Country", :url=>"https://www.indeed.com/q-$40,000-l-Town-'n'-Country,-FL-jobs.html"},
    {:name=>"Largo", :url=>"https://www.indeed.com/q-$40,000-l-Largo,-FL-jobs.html"},
    {:name=>"Melbourne", :url=>"https://www.indeed.com/q-$40,000-l-Melbourne,-FL-jobs.html"},
    {:name=>"The Villages", :url=>"https://www.indeed.com/q-$40,000-l-The-Villages,-FL-jobs.html"},
    {:name=>"Deerfield Beach", :url=>"https://www.indeed.com/q-$40,000-l-Deerfield-Beach,-FL-jobs.html"},
    {:name=>"Boynton Beach", :url=>"https://www.indeed.com/q-$40,000-l-Boynton-Beach,-FL-jobs.html"},
    {:name=>"Pine Hills", :url=>"https://www.indeed.com/q-$40,000-l-Pine-Hills,-FL-jobs.html"},
    {:name=>"Kissimmee", :url=>"https://www.indeed.com/q-$40,000-l-Kissimmee,-FL-jobs.html"},
    {:name=>"Kendall", :url=>"https://www.indeed.com/q-$40,000-l-Kendall,-FL-jobs.html"},
    {:name=>"Lauderhill", :url=>"https://www.indeed.com/q-$40,000-l-Lauderhill,-FL-jobs.html"},
    {:name=>"Homestead", :url=>""},
    {:name=>"North Port", :url=>"https://www.indeed.com/q-$40,000-l-North-Port,-FL-jobs.html"},
    {:name=>"Weston", :url=>"https://www.indeed.com/q-$40,000-l-Weston,-FL-jobs.html"},
    {:name=>"Delray Beach", :url=>"https://www.indeed.com/q-$40,000-l-Delray-Beach,-FL-jobs.html"},
    {:name=>"Poinciana", :url=>"https://www.indeed.com/q-$40,000-l-Poinciana,-FL-jobs.html"},
    {:name=>"Daytona Beach", :url=>"https://www.indeed.com/q-$40,000-l-Daytona-Beach,-FL-jobs.html"},
    {:name=>"Port Orange", :url=>"https://www.indeed.com/q-$40,000-l-Port-Orange,-FL-jobs.html"},
    {:name=>"Tamarac", :url=>"https://www.indeed.com/q-$40,000-l-Tamarac,-FL-jobs.html"},
    {:name=>"Jupiter", :url=>"https://www.indeed.com/q-$40,000-l-Jupiter,-FL-jobs.html"},
    {:name=>"Doral", :url=>"https://www.indeed.com/q-$40,000-l-Doral,-FL-jobs.html"},
    {:name=>"Wellington", :url=>"https://www.indeed.com/q-$40,000-l-Wellington,-FL-jobs.html"},
    {:name=>"Coconut Creek", :url=>"https://www.indeed.com/q-$40,000-l-Coconut-Creek,-FL-jobs.html"},
    {:name=>"Port Charlotte", :url=>"https://www.indeed.com/q-$40,000-l-Port-Charlotte,-FL-jobs.html"},
    {:name=>"Palm Harbor", :url=>"https://www.indeed.com/q-$40,000-l-Palm-Harbor,-FL-jobs.html"},
    {:name=>"North Miami", :url=>"https://www.indeed.com/q-$40,000-l-North-Miami,-FL-jobs.html"},
    {:name=>"The Hammocks", :url=>"https://www.indeed.com/q-$40,000-l-The-Hammocks,-FL-jobs.html"},
    {:name=>"Fountainebleau", :url=>"https://www.indeed.com/q-$40,000-l-Fountainebleau,-FL-jobs.html"},
    {:name=>"Ocala", :url=>"https://www.indeed.com/q-$40,000-l-Ocala,-FL-jobs.html"},
    {:name=>"Sanford", :url=>"https://www.indeed.com/q-$40,000-l-Sanford,-FL-jobs.html"},
    {:name=>"Bradenton", :url=>"https://www.indeed.com/q-$40,000-l-Bradenton,-FL-jobs.html"},
    {:name=>"Bonita Springs", :url=>"https://www.indeed.com/q-$40,000-l-Bonita-Springs,-FL-jobs.html"},
    {:name=>"St. Cloud", :url=>"https://www.indeed.com/q-$40,000-l-St.-Cloud,-FL-jobs.html"},
    {:name=>"Margate", :url=>"https://www.indeed.com/q-$40,000-l-Margate,-FL-jobs.html"},
    {:name=>"Sarasota", :url=>"https://www.indeed.com/q-$40,000-l-Sarasota,-FL-jobs.html"},
    {:name=>"Wesley Chapel", :url=>"https://www.indeed.com/q-$40,000-l-Wesley-Chapel,-FL-jobs.html"},
    {:name=>"Kendale Lakes", :url=>"https://www.indeed.com/q-$40,000-l-Kendale-Lakes,-FL-jobs.html"},
    {:name=>"Palm Beach Gardens", :url=>"https://www.indeed.com/q-$40,000-l-Palm-Beach-Gardens,-FL-jobs.html"},
    {:name=>"Tamiami", :url=>"https://www.indeed.com/q-$40,000-l-Tamiami,-FL-jobs.html"},
    {:name=>"Apopka", :url=>"https://www.indeed.com/q-$40,000-l-Apopka,-FL-jobs.html"},
    {:name=>"Pinellas Park", :url=>"https://www.indeed.com/q-$40,000-l-Pinellas-Park,-FL-jobs.html"},
    {:name=>"Pensacola", :url=>"https://www.indeed.com/q-$40,000-l-Pensacola,-FL-jobs.html"},
    {:name=>"Coral Gables", :url=>"https://www.indeed.com/q-$40,000-l-Coral-Gables,-FL-jobs.html"},
    {:name=>"Ocoee", :url=>"https://www.indeed.com/q-$40,000-l-Ocoee,-FL-jobs.html"},
    {:name=>"Country Club", :url=>"https://www.indeed.com/q-$40,000-l-Country-Club,-FL-jobs.html"},
    {:name=>"University", :url=>"https://www.indeed.com/q-$40,000-l-University,-FL-jobs.html"},
    {:name=>"Titusville", :url=>"https://www.indeed.com/q-$40,000-l-Titusville,-FL-jobs.html"},
    {:name=>"Winter Garden", :url=>"https://www.indeed.com/q-$40,000-l-Winter-Garden,-FL-jobs.html"},
    {:name=>"Fort Pierce", :url=>"https://www.indeed.com/q-$40,000-l-Fort-Pierce,-FL-jobs.html"},
    {:name=>"Oakland Park", :url=>"https://www.indeed.com/q-$40,000-l-Oakland-Park,-FL-jobs.html"},
    {:name=>"North Miami Beach", :url=>"https://www.indeed.com/q-$40,000-l-North-Miami-Beach,-FL-jobs.html"},
    {:name=>"Winter Haven", :url=>"https://www.indeed.com/q-$40,000-l-Winter-Haven,-FL-jobs.html"},
    {:name=>"Altamonte Springs", :url=>"https://www.indeed.com/q-$40,000-l-Altamonte-Springs,-FL-jobs.html"},
    {:name=>"North Lauderdale", :url=>"https://www.indeed.com/q-$40,000-l-North-Lauderdale,-FL-jobs.html"},
    {:name=>"Ormond Beach", :url=>"https://www.indeed.com/q-$40,000-l-Ormond-Beach,-FL-jobs.html"},
    {:name=>"Cutler Bay", :url=>"https://www.indeed.com/q-$40,000-l-Cutler-Bay,-FL-jobs.html"},
    {:name=>"Oviedo", :url=>"https://www.indeed.com/q-$40,000-l-Oviedo,-FL-jobs.html"},
    {:name=>"North Fort Myers", :url=>"https://www.indeed.com/q-$40,000-l-North-Fort-Myers,-FL-jobs.html"},
    {:name=>"Greenacres", :url=>"https://www.indeed.com/q-$40,000-l-Greenacres,-FL-jobs.html"},
    {:name=>"Four Corners", :url=>"https://www.indeed.com/q-$40,000-l-Four-Corners,-FL-jobs.html"},
    {:name=>"Royal Palm Beach", :url=>"https://www.indeed.com/q-$40,000-l-Royal-Palm-Beach,-FL-jobs.html"},
    {:name=>"Hallandale Beach", :url=>"https://www.indeed.com/q-$40,000-l-Hallandale-Beach,-FL-jobs.html"},
    {:name=>"Clermont", :url=>"https://www.indeed.com/q-$40,000-l-Clermont,-FL-jobs.html"},
    {:name=>"The Acreage", :url=>"https://www.indeed.com/q-$40,000-l-The-Acreage,-FL-jobs.html"},
    {:name=>"Plant City", :url=>"https://www.indeed.com/q-$40,000-l-Plant-City,-FL-jobs.html"},
    {:name=>"Kendall West", :url=>"https://www.indeed.com/q-$40,000-l-Kendall-West,-FL-jobs.html"},
    {:name=>"Meadow Woods", :url=>"https://www.indeed.com/q-$40,000-l-Meadow-Woods,-FL-jobs.html"},
    {:name=>"Winter Springs", :url=>"https://www.indeed.com/q-$40,000-l-Winter-Springs,-FL-jobs.html"},
    {:name=>"Richmond West", :url=>"https://www.indeed.com/q-$40,000-l-Richmond-West,-FL-jobs.html"},
    {:name=>"Lauderdale Lakes", :url=>"https://www.indeed.com/q-$40,000-l-Lauderdale-Lakes,-FL-jobs.html"},
    {:name=>"Valrico", :url=>"https://www.indeed.com/q-$40,000-l-Valrico,-FL-jobs.html"},
    {:name=>"Lake Worth", :url=>"https://www.indeed.com/q-$40,000-l-Lake-Worth,-FL-jobs.html"},
    {:name=>"Horizon West", :url=>"https://www.indeed.com/q-$40,000-l-Horizon-West,-FL-jobs.html"},
    {:name=>"Land O' Lakes", :url=>"https://www.indeed.com/q-$40,000-l-Land-O'-Lakes,-FL-jobs.html"},
    {:name=>"Aventura", :url=>"https://www.indeed.com/q-$40,000-l-Aventura,-FL-jobs.html"},
    {:name=>"University", :url=>"https://www.indeed.com/q-$40,000-l-University,-FL-jobs.html"},
    {:name=>"South Miami Heights", :url=>"https://www.indeed.com/q-$40,000-l-South-Miami-Heights,-FL-jobs.html"},
    {:name=>"Merritt Island", :url=>"https://www.indeed.com/q-$40,000-l-Merritt-Island,-FL-jobs.html"},
    {:name=>"EgyLake-Leto", :url=>"https://www.indeed.com/q-$40,000-l-EgyLake-Leto,-FL-jobs.html"},
    {:name=>"Dunedin", :url=>"https://www.indeed.com/q-$40,000-l-Dunedin,-FL-jobs.html"},
    {:name=>"Parkland", :url=>"https://www.indeed.com/q-$40,000-l-Parkland,-FL-jobs.html"},
    {:name=>"Navarre", :url=>"https://www.indeed.com/q-$40,000-l-Navarre,-FL-jobs.html"},
    {:name=>"Panama City", :url=>"https://www.indeed.com/q-$40,000-l-Panama-City,-FL-jobs.html"},
    {:name=>"Cooper City", :url=>"https://www.indeed.com/q-$40,000-l-Cooper-City,-FL-jobs.html"},
    {:name=>"Ferry Pass", :url=>"https://www.indeed.com/q-$40,000-l-Ferry-Pass,-FL-jobs.html"},
    {:name=>"DeLand", :url=>"https://www.indeed.com/q-$40,000-l-DeLand,-FL-jobs.html"},
    {:name=>"Buenaventura Lakes", :url=>"https://www.indeed.com/q-$40,000-l-Buenaventura-Lakes,-FL-jobs.html"},
    {:name=>"Carrollwood", :url=>"https://www.indeed.com/q-$40,000-l-Carrollwood,-FL-jobs.html"},
    {:name=>"Golden Glades", :url=>"https://www.indeed.com/q-$40,000-l-Golden-Glades,-FL-jobs.html"},
    {:name=>"Riviera Beach", :url=>"https://www.indeed.com/q-$40,000-l-Riviera-Beach,-FL-jobs.html"},
    {:name=>"West Little River", :url=>"https://www.indeed.com/q-$40,000-l-West-Little-River,-FL-jobs.html"},
    {:name=>"Fruit Cove", :url=>"https://www.indeed.com/q-$40,000-l-Fruit-Cove,-FL-jobs.html"},
    {:name=>"Dania Beach", :url=>"https://www.indeed.com/q-$40,000-l-Dania-Beach,-FL-jobs.html"},
    {:name=>"Princeton", :url=>"https://www.indeed.com/q-$40,000-l-Princeton,-FL-jobs.html"},
    {:name=>"Winter Park", :url=>"https://www.indeed.com/q-$40,000-l-Winter-Park,-FL-jobs.html"},
    {:name=>"East Lake", :url=>"https://www.indeed.com/q-$40,000-l-East-Lake,-FL-jobs.html"},
    {:name=>"Miami Lakes", :url=>"https://www.indeed.com/q-$40,000-l-Miami-Lakes,-FL-jobs.html"},
    {:name=>"Casselberry", :url=>"https://www.indeed.com/q-$40,000-l-Casselberry,-FL-jobs.html"},
    {:name=>"Lakeside", :url=>"https://www.indeed.com/q-$40,000-l-Lakeside,-FL-jobs.html"},
    {:name=>"Golden Gate", :url=>"https://www.indeed.com/q-$40,000-l-Golden-Gate,-FL-jobs.html"},
    {:name=>"East Lake-Orient Park", :url=>"https://www.indeed.com/q-$40,000-l-East-Lake-Orient-Park,-FL-jobs.html"},
    {:name=>"Westchester", :url=>"https://www.indeed.com/q-$40,000-l-Westchester,-FL-jobs.html"},
    {:name=>"Lake Magdalene", :url=>"https://www.indeed.com/q-$40,000-l-Lake-Magdalene,-FL-jobs.html"},
    {:name=>"Oakleaf Plantation", :url=>"https://www.indeed.com/q-$40,000-l-Oakleaf-Plantation,-FL-jobs.html"},
    {:name=>"Rockledge", :url=>"https://www.indeed.com/q-$40,000-l-Rockledge,-FL-jobs.html"},
    {:name=>"New Smyrna Beach", :url=>"https://www.indeed.com/q-$40,000-l-New-Smyrna-Beach,-FL-jobs.html"},
    {:name=>"Fleming Island", :url=>"https://www.indeed.com/q-$40,000-l-Fleming-Island,-FL-jobs.html"},
    {:name=>"Immokalee", :url=>"https://www.indeed.com/q-$40,000-l-Immokalee,-FL-jobs.html"},
    {:name=>"Bayonet Point", :url=>"https://www.indeed.com/q-$40,000-l-Bayonet-Point,-FL-jobs.html"},
    {:name=>"Citrus Park", :url=>"https://www.indeed.com/q-$40,000-l-Citrus-Park,-FL-jobs.html"},
    {:name=>"Leisure City", :url=>"https://www.indeed.com/q-$40,000-l-Leisure-City,-FL-jobs.html"},
    {:name=>"South Bradenton", :url=>"https://www.indeed.com/q-$40,000-l-South-Bradenton,-FL-jobs.html"},
    {:name=>"Sebastian", :url=>"https://www.indeed.com/q-$40,000-l-Sebastian,-FL-jobs.html"},
    {:name=>"Haines City", :url=>"https://www.indeed.com/q-$40,000-l-Haines-City,-FL-jobs.html"},
    {:name=>"Temple Terrace", :url=>"https://www.indeed.com/q-$40,000-l-Temple-Terrace,-FL-jobs.html"},
    {:name=>"University Park", :url=>"https://www.indeed.com/q-$40,000-l-University-Park,-FL-jobs.html"},
    {:name=>"Tarpon Springs", :url=>"https://www.indeed.com/q-$40,000-l-Tarpon-Springs,-FL-jobs.html"},
    {:name=>"Palm City", :url=>"https://www.indeed.com/q-$40,000-l-Palm-City,-FL-jobs.html"},
    {:name=>"Crestview", :url=>"https://www.indeed.com/q-$40,000-l-Crestview,-FL-jobs.html"},
    {:name=>"Keystone", :url=>"https://www.indeed.com/q-$40,000-l-Keystone,-FL-jobs.html"},
    {:name=>"Palm Springs", :url=>"https://www.indeed.com/q-$40,000-l-Palm-Springs,-FL-jobs.html"},
    {:name=>"Ruskin", :url=>"https://www.indeed.com/q-$40,000-l-Ruskin,-FL-jobs.html"},
    {:name=>"Coral Terrace", :url=>"https://www.indeed.com/q-$40,000-l-Coral-Terrace,-FL-jobs.html"},
    {:name=>"West Melbourne", :url=>"https://www.indeed.com/q-$40,000-l-West-Melbourne,-FL-jobs.html"},
    {:name=>"Sun City Center", :url=>"https://www.indeed.com/q-$40,000-l-Sun-City-Center,-FL-jobs.html"},
    {:name=>"Pace", :url=>"https://www.indeed.com/q-$40,000-l-Pace,-FL-jobs.html"},
    {:name=>"Palmetto Bay", :url=>"https://www.indeed.com/q-$40,000-l-Palmetto-Bay,-FL-jobs.html"},
    {:name=>"Vero Beach South", :url=>"https://www.indeed.com/q-$40,000-l-Vero-Beach-South,-FL-jobs.html"},
    {:name=>"Venice", :url=>"https://www.indeed.com/q-$40,000-l-Venice,-FL-jobs.html"},
    {:name=>"Oak Ridge", :url=>"https://www.indeed.com/q-$40,000-l-Oak-Ridge,-FL-jobs.html"},
    {:name=>"Key West", :url=>"https://www.indeed.com/q-$40,000-l-Key-West,-FL-jobs.html"},
    {:name=>"Hialeah Gardens", :url=>"https://www.indeed.com/q-$40,000-l-Hialeah-Gardens,-FL-jobs.html"},
    {:name=>"Bloomingdale", :url=>"https://www.indeed.com/q-$40,000-l-Bloomingdale,-FL-jobs.html"},
    {:name=>"Jacksonville Beach", :url=>"https://www.indeed.com/q-$40,000-l-Jacksonville-Beach,-FL-jobs.html"},
    {:name=>"Palm River-Clair Mel", :url=>"https://www.indeed.com/q-$40,000-l-Palm-River-Clair-Mel,-FL-jobs.html"},
    {:name=>"Leesburg", :url=>"https://www.indeed.com/q-$40,000-l-Leesburg,-FL-jobs.html"},
    {:name=>"Westchase", :url=>"https://www.indeed.com/q-$40,000-l-Westchase,-FL-jobs.html"},
    {:name=>"Ives Estates", :url=>"https://www.indeed.com/q-$40,000-l-Ives-Estates,-FL-jobs.html"},
    {:name=>"Ensley", :url=>"https://www.indeed.com/q-$40,000-l-Ensley,-FL-jobs.html"},
    {:name=>"Hunters Creek", :url=>"https://www.indeed.com/q-$40,000-l-Hunters-Creek,-FL-jobs.html"},
    {:name=>"Edgewater", :url=>"https://www.indeed.com/q-$40,000-l-Edgewater,-FL-jobs.html"},
    {:name=>"The Crossings", :url=>"https://www.indeed.com/q-$40,000-l-The-Crossings,-FL-jobs.html"},
    {:name=>"Wekiwa Springs", :url=>"https://www.indeed.com/q-$40,000-l-Wekiwa-Springs,-FL-jobs.html"},
    {:name=>"Jasmine Estates", :url=>"https://www.indeed.com/q-$40,000-l-Jasmine-Estates,-FL-jobs.html"},
    {:name=>"Fort Walton Beach", :url=>"https://www.indeed.com/q-$40,000-l-Fort-Walton-Beach,-FL-jobs.html"},
    {:name=>"Florida Ridge", :url=>"https://www.indeed.com/q-$40,000-l-Florida-Ridge,-FL-jobs.html"},
    {:name=>"Northdale", :url=>"https://www.indeed.com/q-$40,000-l-Northdale,-FL-jobs.html"},
    {:name=>"Sunny Isles Beach", :url=>"https://www.indeed.com/q-$40,000-l-Sunny-Isles-Beach,-FL-jobs.html"},
    {:name=>"Naples", :url=>"https://www.indeed.com/q-$40,000-l-Naples,-FL-jobs.html"},
    {:name=>"Lynn Haven", :url=>"https://www.indeed.com/q-$40,000-l-Lynn-Haven,-FL-jobs.html"},
    {:name=>"Wright", :url=>"https://www.indeed.com/q-$40,000-l-Wright,-FL-jobs.html"},
    {:name=>"Brent", :url=>"https://www.indeed.com/q-$40,000-l-Brent,-FL-jobs.html"},
    {:name=>"Lutz", :url=>"https://www.indeed.com/q-$40,000-l-Lutz,-FL-jobs.html"},
    {:name=>"West Pensacola", :url=>"https://www.indeed.com/q-$40,000-l-West-Pensacola,-FL-jobs.html"},
    {:name=>"Palm Valley", :url=>"https://www.indeed.com/q-$40,000-l-Palm-Valley,-FL-jobs.html"},
    {:name=>"DeBary", :url=>"https://www.indeed.com/q-$40,000-l-DeBary,-FL-jobs.html"},
    {:name=>"Fish Hawk", :url=>"https://www.indeed.com/q-$40,000-l-Fish-Hawk,-FL-jobs.html"},
    {:name=>"Eustis", :url=>"https://www.indeed.com/q-$40,000-l-Eustis,-FL-jobs.html"},
    {:name=>"Holiday", :url=>"https://www.indeed.com/q-$40,000-l-Holiday,-FL-jobs.html"},
    {:name=>"Sweetwater", :url=>"https://www.indeed.com/q-$40,000-l-Sweetwater,-FL-jobs.html"},
    {:name=>"Lealman", :url=>"https://www.indeed.com/q-$40,000-l-Lealman,-FL-jobs.html"},
    {:name=>"Bayshore Gardens", :url=>"https://www.indeed.com/q-$40,000-l-Bayshore-Gardens,-FL-jobs.html"},
    {:name=>"Punta Gorda", :url=>"https://www.indeed.com/q-$40,000-l-Punta-Gorda,-FL-jobs.html"},
    {:name=>"Apollo Beach", :url=>"https://www.indeed.com/q-$40,000-l-Apollo-Beach,-FL-jobs.html"},
    {:name=>"Belle Glade", :url=>"https://www.indeed.com/q-$40,000-l-Belle-Glade,-FL-jobs.html"},
    {:name=>"Bellview", :url=>"https://www.indeed.com/q-$40,000-l-Bellview,-FL-jobs.html"},
    {:name=>"Bartow", :url=>"https://www.indeed.com/q-$40,000-l-Bartow,-FL-jobs.html"},
    {:name=>"Lake Butler", :url=>"https://www.indeed.com/q-$40,000-l-Lake-Butler,-FL-jobs.html"},
    {:name=>"Pinecrest", :url=>"https://www.indeed.com/q-$40,000-l-Pinecrest,-FL-jobs.html"},
    {:name=>"Cocoa", :url=>"https://www.indeed.com/q-$40,000-l-Cocoa,-FL-jobs.html"},
    {:name=>"Seminole", :url=>"https://www.indeed.com/q-$40,000-l-Seminole,-FL-jobs.html"},
    {:name=>"Tavares", :url=>"https://www.indeed.com/q-$40,000-l-Tavares,-FL-jobs.html"},
    {:name=>"Gibsonton", :url=>"https://www.indeed.com/q-$40,000-l-Gibsonton,-FL-jobs.html"},
    {:name=>"Safety Harbor", :url=>"https://www.indeed.com/q-$40,000-l-Safety-Harbor,-FL-jobs.html"},
    {:name=>"Maitland", :url=>"https://www.indeed.com/q-$40,000-l-Maitland,-FL-jobs.html"},
    {:name=>"Marco Island", :url=>"https://www.indeed.com/q-$40,000-l-Marco-Island,-FL-jobs.html"},
    {:name=>"Brownsville", :url=>"https://www.indeed.com/q-$40,000-l-Brownsville,-FL-jobs.html"},
    {:name=>"Upper Grand Lagoon", :url=>"https://www.indeed.com/q-$40,000-l-Upper-Grand-Lagoon,-FL-jobs.html"},
    {:name=>"Vero Beach", :url=>"https://www.indeed.com/q-$40,000-l-Vero-Beach,-FL-jobs.html"},
    {:name=>"San Carlos Park", :url=>"https://www.indeed.com/q-$40,000-l-San-Carlos-Park,-FL-jobs.html"},
    {:name=>"World Golf Village", :url=>"https://www.indeed.com/q-$40,000-l-World-Golf-Village,-FL-jobs.html"},
    {:name=>"Midway", :url=>"https://www.indeed.com/q-$40,000-l-Midway,-FL-jobs.html"},
    {:name=>"Lake Mary", :url=>"https://www.indeed.com/q-$40,000-l-Lake-Mary,-FL-jobs.html"},
    {:name=>"Auburndale", :url=>"https://www.indeed.com/q-$40,000-l-Auburndale,-FL-jobs.html"},
    {:name=>"Glenvar Heights", :url=>"https://www.indeed.com/q-$40,000-l-Glenvar-Heights,-FL-jobs.html"},
    {:name=>"Lake Wales", :url=>"https://www.indeed.com/q-$40,000-l-Lake-Wales,-FL-jobs.html"},
    {:name=>"Pinewood", :url=>"https://www.indeed.com/q-$40,000-l-Pinewood,-FL-jobs.html"},
    {:name=>"Country Walk", :url=>"https://www.indeed.com/q-$40,000-l-Country-Walk,-FL-jobs.html"},
    {:name=>"New Port Richey", :url=>"https://www.indeed.com/q-$40,000-l-New-Port-Richey,-FL-jobs.html"},
    {:name=>"Ojus", :url=>"https://www.indeed.com/q-$40,000-l-Ojus,-FL-jobs.html"},
    {:name=>"Groveland", :url=>"https://www.indeed.com/q-$40,000-l-Groveland,-FL-jobs.html"},
    {:name=>"Myrtle Grove", :url=>"https://www.indeed.com/q-$40,000-l-Myrtle-Grove,-FL-jobs.html"},
    {:name=>"Stuart", :url=>"https://www.indeed.com/q-$40,000-l-Stuart,-FL-jobs.html"},
    {:name=>"Zephyrhills", :url=>"https://www.indeed.com/q-$40,000-l-Zephyrhills,-FL-jobs.html"},
    {:name=>"Opa-locka", :url=>"https://www.indeed.com/q-$40,000-l-Opa-locka,-FL-jobs.html"},
    {:name=>"Nocatee", :url=>"https://www.indeed.com/q-$40,000-l-Nocatee,-FL-jobs.html"},
    {:name=>"Niceville", :url=>"https://www.indeed.com/q-$40,000-l-Niceville,-FL-jobs.html"},
    {:name=>"Palmetto Estates", :url=>"https://www.indeed.com/q-$40,000-l-Palmetto-Estates,-FL-jobs.html"},
    {:name=>"Three Lakes", :url=>"https://www.indeed.com/q-$40,000-l-Three-Lakes,-FL-jobs.html"},
    {:name=>"Lady Lake", :url=>"https://www.indeed.com/q-$40,000-l-Lady-Lake,-FL-jobs.html"},
    {:name=>"Sarasota Springs", :url=>"https://www.indeed.com/q-$40,000-l-Sarasota-Springs,-FL-jobs.html"},
    {:name=>"Bellair-Meadowbrook Terrace", :url=>"https://www.indeed.com/q-$40,000-l-Bellair-Meadowbrook-Terrace,-FL-jobs.html"},
    {:name=>"Englewood", :url=>"https://www.indeed.com/q-$40,000-l-Englewood,-FL-jobs.html"},
    {:name=>"Azalea Park", :url=>"https://www.indeed.com/q-$40,000-l-Azalea-Park,-FL-jobs.html"},
    {:name=>"West Park", :url=>"https://www.indeed.com/q-$40,000-l-West-Park,-FL-jobs.html"},
    {:name=>"Longwood", :url=>"https://www.indeed.com/q-$40,000-l-Longwood,-FL-jobs.html"},
    {:name=>"Sunset", :url=>"https://www.indeed.com/q-$40,000-l-Sunset,-FL-jobs.html"},
    {:name=>"Oldsmar", :url=>"https://www.indeed.com/q-$40,000-l-Oldsmar,-FL-jobs.html"},
    {:name=>"Callaway", :url=>"https://www.indeed.com/q-$40,000-l-Callaway,-FL-jobs.html"},
    {:name=>"St. Augustine", :url=>"https://www.indeed.com/q-$40,000-l-St.-Augustine,-FL-jobs.html"},
    {:name=>"West Lealman", :url=>"https://www.indeed.com/q-$40,000-l-West-Lealman,-FL-jobs.html"},
    {:name=>"Warrington", :url=>"https://www.indeed.com/q-$40,000-l-Warrington,-FL-jobs.html"},
    {:name=>"Lockhart", :url=>"https://www.indeed.com/q-$40,000-l-Lockhart,-FL-jobs.html"},
    {:name=>"Olympia Heights", :url=>"https://www.indeed.com/q-$40,000-l-Olympia-Heights,-FL-jobs.html"},
    {:name=>"Mount Dora", :url=>"https://www.indeed.com/q-$40,000-l-Mount-Dora,-FL-jobs.html"},
    {:name=>"Iona", :url=>"https://www.indeed.com/q-$40,000-l-Iona,-FL-jobs.html"},
    {:name=>"Southchase", :url=>"https://www.indeed.com/q-$40,000-l-Southchase,-FL-jobs.html"},
    {:name=>"Fruitland Park", :url=>"https://www.indeed.com/q-$40,000-l-Fruitland-Park,-FL-jobs.html"},
    {:name=>"Destin", :url=>"https://www.indeed.com/q-$40,000-l-Destin,-FL-jobs.html"},
    {:name=>"Union Park", :url=>"https://www.indeed.com/q-$40,000-l-Union-Park,-FL-jobs.html"},
    {:name=>"South Venice", :url=>"https://www.indeed.com/q-$40,000-l-South-Venice,-FL-jobs.html"},
    {:name=>"Miami Springs", :url=>"https://www.indeed.com/q-$40,000-l-Miami-Springs,-FL-jobs.html"},
    {:name=>"Hobe Sound", :url=>"https://www.indeed.com/q-$40,000-l-Hobe-Sound,-FL-jobs.html"},
    {:name=>"Forest City", :url=>"https://www.indeed.com/q-$40,000-l-Forest-City,-FL-jobs.html"},
    {:name=>"Atlantic Beach", :url=>"https://www.indeed.com/q-$40,000-l-Atlantic-Beach,-FL-jobs.html"},
    {:name=>"Thonotosassa", :url=>"https://www.indeed.com/q-$40,000-l-Thonotosassa,-FL-jobs.html"},
    {:name=>"Jensen Beach", :url=>"https://www.indeed.com/q-$40,000-l-Jensen-Beach,-FL-jobs.html"},
    {:name=>"Gonzalez", :url=>"https://www.indeed.com/q-$40,000-l-Gonzalez,-FL-jobs.html"},
    {:name=>"Fruitville", :url=>"https://www.indeed.com/q-$40,000-l-Fruitville,-FL-jobs.html"},
    {:name=>"Gladeview", :url=>"https://www.indeed.com/q-$40,000-l-Gladeview,-FL-jobs.html"},
    {:name=>"Palmetto", :url=>"https://www.indeed.com/q-$40,000-l-Palmetto,-FL-jobs.html"},
    {:name=>"East Milton", :url=>"https://www.indeed.com/q-$40,000-l-East-Milton,-FL-jobs.html"},
    {:name=>"Middleburg", :url=>"https://www.indeed.com/q-$40,000-l-Middleburg,-FL-jobs.html"},
    {:name=>"Homosassa Springs", :url=>"https://www.indeed.com/q-$40,000-l-Homosassa-Springs,-FL-jobs.html"},
    {:name=>"Cypress Lake", :url=>"https://www.indeed.com/q-$40,000-l-Cypress-Lake,-FL-jobs.html"},
    {:name=>"Goldenrod", :url=>"https://www.indeed.com/q-$40,000-l-Goldenrod,-FL-jobs.html"},
    {:name=>"Minneola", :url=>"https://www.indeed.com/q-$40,000-l-Minneola,-FL-jobs.html"},
    {:name=>"South Daytona", :url=>"https://www.indeed.com/q-$40,000-l-South-Daytona,-FL-jobs.html"},
    {:name=>"Key Biscayne", :url=>"https://www.indeed.com/q-$40,000-l-Key-Biscayne,-FL-jobs.html"},
    {:name=>"North Palm Beach", :url=>"https://www.indeed.com/q-$40,000-l-North-Palm-Beach,-FL-jobs.html"},
    {:name=>"Panama City Beach", :url=>"https://www.indeed.com/q-$40,000-l-Panama-City-Beach,-FL-jobs.html"},
    {:name=>"Lakewood Park", :url=>"https://www.indeed.com/q-$40,000-l-Lakewood-Park,-FL-jobs.html"},
    {:name=>"Shady Hills", :url=>"https://www.indeed.com/q-$40,000-l-Shady-Hills,-FL-jobs.html"},
    {:name=>"Fernandina Beach", :url=>"https://www.indeed.com/q-$40,000-l-Fernandina-Beach,-FL-jobs.html"},
    {:name=>"Lantana", :url=>"https://www.indeed.com/q-$40,000-l-Lantana,-FL-jobs.html"},
    {:name=>"Yulee", :url=>"https://www.indeed.com/q-$40,000-l-Yulee,-FL-jobs.html"},
    {:name=>"Wilton Manors", :url=>"https://www.indeed.com/q-$40,000-l-Wilton-Manors,-FL-jobs.html"},
    {:name=>"Hudson", :url=>"https://www.indeed.com/q-$40,000-l-Hudson,-FL-jobs.html"},
    {:name=>"Conway", :url=>"https://www.indeed.com/q-$40,000-l-Conway,-FL-jobs.html"},
    {:name=>"Lakeland Highlands", :url=>"https://www.indeed.com/q-$40,000-l-Lakeland-Highlands,-FL-jobs.html"},
    {:name=>"Villas", :url=>"https://www.indeed.com/q-$40,000-l-Villas,-FL-jobs.html"},
    {:name=>"Holly Hill", :url=>"https://www.indeed.com/q-$40,000-l-Holly-Hill,-FL-jobs.html"},
    {:name=>"Gulfport", :url=>"https://www.indeed.com/q-$40,000-l-Gulfport,-FL-jobs.html"},
    {:name=>"Richmond Heights", :url=>"https://www.indeed.com/q-$40,000-l-Richmond-Heights,-FL-jobs.html"},
    {:name=>"Viera West", :url=>"https://www.indeed.com/q-$40,000-l-Viera-West,-FL-jobs.html"},
    {:name=>"South Miami", :url=>"https://www.indeed.com/q-$40,000-l-South-Miami,-FL-jobs.html"},
    {:name=>"Lake City", :url=>"https://www.indeed.com/q-$40,000-l-Lake-City,-FL-jobs.html"},
    {:name=>"Westwood Lakes", :url=>"https://www.indeed.com/q-$40,000-l-Westwood-Lakes,-FL-jobs.html"},
    {:name=>"Orange City", :url=>"https://www.indeed.com/q-$40,000-l-Orange-City,-FL-jobs.html"},
    {:name=>"Jupiter Farms", :url=>"https://www.indeed.com/q-$40,000-l-Jupiter-Farms,-FL-jobs.html"},
    {:name=>"Florida City", :url=>"https://www.indeed.com/q-$40,000-l-Florida-City,-FL-jobs.html"},
    {:name=>"Pine Castle", :url=>"https://www.indeed.com/q-$40,000-l-Pine-Castle,-FL-jobs.html"},
    {:name=>"Elfers", :url=>"https://www.indeed.com/q-$40,000-l-Elfers,-FL-jobs.html"},
    {:name=>"Cocoa Beach", :url=>"https://www.indeed.com/q-$40,000-l-Cocoa-Beach,-FL-jobs.html"},
    {:name=>"Port St. John", :url=>"https://www.indeed.com/q-$40,000-l-Port-St.-John,-FL-jobs.html"},
    {:name=>"Port Salerno", :url=>"https://www.indeed.com/q-$40,000-l-Port-Salerno,-FL-jobs.html"},
    {:name=>"Satellite Beach", :url=>"https://www.indeed.com/q-$40,000-l-Satellite-Beach,-FL-jobs.html"},
    {:name=>"Naranja", :url=>"https://www.indeed.com/q-$40,000-l-Naranja,-FL-jobs.html"},
    {:name=>"Fairview Shores", :url=>"https://www.indeed.com/q-$40,000-l-Fairview-Shores,-FL-jobs.html"},
    {:name=>"Goulds", :url=>"https://www.indeed.com/q-$40,000-l-Goulds,-FL-jobs.html"},
    {:name=>"Lighthouse Point", :url=>"https://www.indeed.com/q-$40,000-l-Lighthouse-Point,-FL-jobs.html"},
    {:name=>"Gateway", :url=>"https://www.indeed.com/q-$40,000-l-Gateway,-FL-jobs.html"},
    {:name=>"Progress Village", :url=>"https://www.indeed.com/q-$40,000-l-Progress-Village,-FL-jobs.html"},
    {:name=>"Westview", :url=>"https://www.indeed.com/q-$40,000-l-Westview,-FL-jobs.html"},
    {:name=>"Sebring", :url=>"https://www.indeed.com/q-$40,000-l-Sebring,-FL-jobs.html"},
    {:name=>"Viera East", :url=>"https://www.indeed.com/q-$40,000-l-Viera-East,-FL-jobs.html"},
    {:name=>"Doctor Phillips", :url=>"https://www.indeed.com/q-$40,000-l-Doctor-Phillips,-FL-jobs.html"},
    {:name=>"Avon Park", :url=>"https://www.indeed.com/q-$40,000-l-Avon-Park,-FL-jobs.html"},
    {:name=>"Gulf Gate Estates", :url=>"https://www.indeed.com/q-$40,000-l-Gulf-Gate-Estates,-FL-jobs.html"},
    {:name=>"Pasadena Hills", :url=>"https://www.indeed.com/q-$40,000-l-Pasadena-Hills,-FL-jobs.html"},
    {:name=>"Cypress Gardens", :url=>"https://www.indeed.com/q-$40,000-l-Cypress-Gardens,-FL-jobs.html"},
    {:name=>"Mango", :url=>"https://www.indeed.com/q-$40,000-l-Mango,-FL-jobs.html"},
    {:name=>"Highland City", :url=>"https://www.indeed.com/q-$40,000-l-Highland-City,-FL-jobs.html"},
    {:name=>"New Port Richey East", :url=>"https://www.indeed.com/q-$40,000-l-New-Port-Richey-East,-FL-jobs.html"},
    {:name=>"Milton", :url=>"https://www.indeed.com/q-$40,000-l-Milton,-FL-jobs.html"},
    {:name=>"Fuller Heights", :url=>"https://www.indeed.com/q-$40,000-l-Fuller-Heights,-FL-jobs.html"},
    {:name=>"Trinity", :url=>"https://www.indeed.com/q-$40,000-l-Trinity,-FL-jobs.html"},
    {:name=>"Palatka", :url=>"https://www.indeed.com/q-$40,000-l-Palatka,-FL-jobs.html"},
    {:name=>"Westgate", :url=>"https://www.indeed.com/q-$40,000-l-Westgate,-FL-jobs.html"},
    {:name=>"Cape Canaveral", :url=>"https://www.indeed.com/q-$40,000-l-Cape-Canaveral,-FL-jobs.html"},
    {:name=>"Pine Ridge", :url=>"https://www.indeed.com/q-$40,000-l-Pine-Ridge,-FL-jobs.html"},
    {:name=>"West Perrine", :url=>"https://www.indeed.com/q-$40,000-l-West-Perrine,-FL-jobs.html"},
    {:name=>"Miami Shores", :url=>"https://www.indeed.com/q-$40,000-l-Miami-Shores,-FL-jobs.html"},
    {:name=>"Cheval", :url=>"https://www.indeed.com/q-$40,000-l-Cheval,-FL-jobs.html"},
    {:name=>"Medulla", :url=>"https://www.indeed.com/q-$40,000-l-Medulla,-FL-jobs.html"},
    {:name=>"Celebration", :url=>"https://www.indeed.com/q-$40,000-l-Celebration,-FL-jobs.html"},
    {:name=>"Alachua", :url=>"https://www.indeed.com/q-$40,000-l-Alachua,-FL-jobs.html"},
    {:name=>"Bee Ridge", :url=>"https://www.indeed.com/q-$40,000-l-Bee-Ridge,-FL-jobs.html"},
    {:name=>"St. Augustine Shores", :url=>"https://www.indeed.com/q-$40,000-l-St.-Augustine-Shores,-FL-jobs.html"},
    {:name=>"Asbury Lake", :url=>"https://www.indeed.com/q-$40,000-l-Asbury-Lake,-FL-jobs.html"},
    {:name=>"Silver Springs Shores", :url=>"https://www.indeed.com/q-$40,000-l-Silver-Springs-Shores,-FL-jobs.html"},
    {:name=>"Gifford", :url=>"https://www.indeed.com/q-$40,000-l-Gifford,-FL-jobs.html"},
    {:name=>"Bithlo", :url=>"https://www.indeed.com/q-$40,000-l-Bithlo,-FL-jobs.html"},
    {:name=>"Beverly Hills", :url=>"https://www.indeed.com/q-$40,000-l-Beverly-Hills,-FL-jobs.html"},
    {:name=>"St. Pete Beach", :url=>"https://www.indeed.com/q-$40,000-l-St.-Pete-Beach,-FL-jobs.html"},
    {:name=>"Laurel", :url=>"https://www.indeed.com/q-$40,000-l-Laurel,-FL-jobs.html"},
    {:name=>"Key Largo", :url=>"https://www.indeed.com/q-$40,000-l-Key-Largo,-FL-jobs.html"},
    {:name=>"North Sarasota", :url=>"https://www.indeed.com/q-$40,000-l-North-Sarasota,-FL-jobs.html"},
    {:name=>"Miramar Beach", :url=>"https://www.indeed.com/q-$40,000-l-Miramar-Beach,-FL-jobs.html"},
    {:name=>"Bardmoor", :url=>"https://www.indeed.com/q-$40,000-l-Bardmoor,-FL-jobs.html"},
    {:name=>"Springfield", :url=>"https://www.indeed.com/q-$40,000-l-Springfield,-FL-jobs.html"},
    {:name=>"West Miami", :url=>"https://www.indeed.com/q-$40,000-l-West-Miami,-FL-jobs.html"},
    {:name=>"Seffner", :url=>"https://www.indeed.com/q-$40,000-l-Seffner,-FL-jobs.html"},
    {:name=>"West Vero Corridor", :url=>"https://www.indeed.com/q-$40,000-l-West-Vero-Corridor,-FL-jobs.html"},
    {:name=>"Micco", :url=>"https://www.indeed.com/q-$40,000-l-Micco,-FL-jobs.html"},
    {:name=>"Green Cove Springs", :url=>"https://www.indeed.com/q-$40,000-l-Green-Cove-Springs,-FL-jobs.html"},
    {:name=>"Rotonda", :url=>"https://www.indeed.com/q-$40,000-l-Rotonda,-FL-jobs.html"},
    {:name=>"Odessa", :url=>"https://www.indeed.com/q-$40,000-l-Odessa,-FL-jobs.html"},
    {:name=>"Orange Park", :url=>"https://www.indeed.com/q-$40,000-l-Orange-Park,-FL-jobs.html"},
    {:name=>"Palm Beach", :url=>"https://www.indeed.com/q-$40,000-l-Palm-Beach,-FL-jobs.html"},
    {:name=>"Memphis", :url=>"https://www.indeed.com/q-$40,000-l-Memphis,-FL-jobs.html"},
    {:name=>"Venice Gardens", :url=>"https://www.indeed.com/q-$40,000-l-Venice-Gardens,-FL-jobs.html"},
    {:name=>"Indian Harbour Beach", :url=>"https://www.indeed.com/q-$40,000-l-Indian-Harbour-Beach,-FL-jobs.html"},
    {:name=>"Lake Park", :url=>"https://www.indeed.com/q-$40,000-l-Lake-Park,-FL-jobs.html"},
    {:name=>"Marathon", :url=>"https://www.indeed.com/q-$40,000-l-Marathon,-FL-jobs.html"},
    {:name=>"Arcadia", :url=>"https://www.indeed.com/q-$40,000-l-Arcadia,-FL-jobs.html"},
    {:name=>"Sugarmill Woods", :url=>"https://www.indeed.com/q-$40,000-l-Sugarmill-Woods,-FL-jobs.html"},
    {:name=>"Hernando", :url=>"https://www.indeed.com/q-$40,000-l-Hernando,-FL-jobs.html"},
    {:name=>"Brooksville", :url=>"https://www.indeed.com/q-$40,000-l-Brooksville,-FL-jobs.html"},
    {:name=>"Fern Park", :url=>"https://www.indeed.com/q-$40,000-l-Fern-Park,-FL-jobs.html"},
    {:name=>"Broadview Park", :url=>"https://www.indeed.com/q-$40,000-l-Broadview-Park,-FL-jobs.html"},
    {:name=>"Citrus Springs", :url=>"https://www.indeed.com/q-$40,000-l-Citrus-Springs,-FL-jobs.html"},
    {:name=>"Clewiston", :url=>"https://www.indeed.com/q-$40,000-l-Clewiston,-FL-jobs.html"},
    {:name=>"North Bay Village", :url=>"https://www.indeed.com/q-$40,000-l-North-Bay-Village,-FL-jobs.html"},
    {:name=>"Pebble Creek", :url=>"https://www.indeed.com/q-$40,000-l-Pebble-Creek,-FL-jobs.html"},
    {:name=>"McGregor", :url=>"https://www.indeed.com/q-$40,000-l-McGregor,-FL-jobs.html"},
    {:name=>"West Samoset", :url=>"https://www.indeed.com/q-$40,000-l-West-Samoset,-FL-jobs.html"},
    {:name=>"Wimauma", :url=>"https://www.indeed.com/q-$40,000-l-Wimauma,-FL-jobs.html"},
    {:name=>"Inwood", :url=>"https://www.indeed.com/q-$40,000-l-Inwood,-FL-jobs.html"},
    {:name=>"Southwest Ranches", :url=>"https://www.indeed.com/q-$40,000-l-Southwest-Ranches,-FL-jobs.html"},
    {:name=>"Williamsburg", :url=>"https://www.indeed.com/q-$40,000-l-Williamsburg,-FL-jobs.html"},
    {:name=>"Wedgefield", :url=>"https://www.indeed.com/q-$40,000-l-Wedgefield,-FL-jobs.html"},
    {:name=>"Southeast Arcadia", :url=>"https://www.indeed.com/q-$40,000-l-Southeast-Arcadia,-FL-jobs.html"},
    {:name=>"Willow Oak", :url=>"https://www.indeed.com/q-$40,000-l-Willow-Oak,-FL-jobs.html"},
    {:name=>"Fort Myers Shores", :url=>"https://www.indeed.com/q-$40,000-l-Fort-Myers-Shores,-FL-jobs.html"},
    {:name=>"North Weeki Wachee", :url=>"https://www.indeed.com/q-$40,000-l-North-Weeki-Wachee,-FL-jobs.html"},
    {:name=>"Sanibel", :url=>"https://www.indeed.com/q-$40,000-l-Sanibel,-FL-jobs.html"},
    {:name=>"Inverness", :url=>"https://www.indeed.com/q-$40,000-l-Inverness,-FL-jobs.html"},
    {:name=>"Dade City", :url=>"https://www.indeed.com/q-$40,000-l-Dade-City,-FL-jobs.html"},
    {:name=>"Belle Isle", :url=>"https://www.indeed.com/q-$40,000-l-Belle-Isle,-FL-jobs.html"},
    {:name=>"River Park", :url=>"https://www.indeed.com/q-$40,000-l-River-Park,-FL-jobs.html"},
    {:name=>"Wildwood", :url=>"https://www.indeed.com/q-$40,000-l-Wildwood,-FL-jobs.html"},
    {:name=>"Southgate", :url=>"https://www.indeed.com/q-$40,000-l-Southgate,-FL-jobs.html"},
    {:name=>"Longboat Key", :url=>"https://www.indeed.com/q-$40,000-l-Longboat-Key,-FL-jobs.html"},
    {:name=>"Osprey", :url=>"https://www.indeed.com/q-$40,000-l-Osprey,-FL-jobs.html"},
    {:name=>"Nene Beach", :url=>"https://www.indeed.com/q-$40,000-l-Nene-Beach,-FL-jobs.html"},
    {:name=>"Indian River Estates", :url=>"https://www.indeed.com/q-$40,000-l-Indian-River-Estates,-FL-jobs.html"},
    {:name=>"Fort Myers Beach", :url=>"https://www.indeed.com/q-$40,000-l-Fort-Myers-Beach,-FL-jobs.html"},
    {:name=>"DeFuniak Springs", :url=>"https://www.indeed.com/q-$40,000-l-DeFuniak-Springs,-FL-jobs.html"},
    {:name=>"Citrus Hills", :url=>"https://www.indeed.com/q-$40,000-l-Citrus-Hills,-FL-jobs.html"},
    {:name=>"Quincy", :url=>"https://www.indeed.com/q-$40,000-l-Quincy,-FL-jobs.html"},
    {:name=>"St. Augustine Beach", :url=>"https://www.indeed.com/q-$40,000-l-St.-Augustine-Beach,-FL-jobs.html"},
    {:name=>"Ormond-by-the-Sea", :url=>"https://www.indeed.com/q-$40,000-l-Ormond-by-the-Sea,-FL-jobs.html"},
    {:name=>"Fort Pierce North", :url=>"https://www.indeed.com/q-$40,000-l-Fort-Pierce-North,-FL-jobs.html"},
    {:name=>"Marianna", :url=>"https://www.indeed.com/q-$40,000-l-Marianna,-FL-jobs.html"},
    {:name=>"Lake Lorraine", :url=>"https://www.indeed.com/q-$40,000-l-Lake-Lorraine,-FL-jobs.html"},
    {:name=>"Gulf Breeze", :url=>"https://www.indeed.com/q-$40,000-l-Gulf-Breeze,-FL-jobs.html"},
    {:name=>"Live Oak", :url=>"https://www.indeed.com/q-$40,000-l-Live-Oak,-FL-jobs.html"},
    {:name=>"South Patrick Shores", :url=>"https://www.indeed.com/q-$40,000-l-South-Patrick-Shores,-FL-jobs.html"},
    {:name=>"Treasure Island", :url=>"https://www.indeed.com/q-$40,000-l-Treasure-Island,-FL-jobs.html"},
    {:name=>"Lely Resort", :url=>"https://www.indeed.com/q-$40,000-l-Lely-Resort,-FL-jobs.html"},
    {:name=>"Naples Manor", :url=>"https://www.indeed.com/q-$40,000-l-Naples-Manor,-FL-jobs.html"},
    {:name=>"Jan Phyl Village", :url=>"https://www.indeed.com/q-$40,000-l-Jan-Phyl-Village,-FL-jobs.html"},
    {:name=>"Beacon Square", :url=>"https://www.indeed.com/q-$40,000-l-Beacon-Square,-FL-jobs.html"},
    {:name=>"Perry", :url=>"https://www.indeed.com/q-$40,000-l-Perry,-FL-jobs.html"},
    {:name=>"Crystal Lake", :url=>"https://www.indeed.com/q-$40,000-l-Crystal-Lake,-FL-jobs.html"},
    {:name=>"Pembroke Park", :url=>"https://www.indeed.com/q-$40,000-l-Pembroke-Park,-FL-jobs.html"},
    {:name=>"Orlovista", :url=>"https://www.indeed.com/q-$40,000-l-Orlovista,-FL-jobs.html"},
    {:name=>"Macclenny", :url=>"https://www.indeed.com/q-$40,000-l-Macclenny,-FL-jobs.html"},
    {:name=>"Lauderdale-by-the-Sea", :url=>"https://www.indeed.com/q-$40,000-l-Lauderdale-by-the-Sea,-FL-jobs.html"},
    {:name=>"Cocoa West", :url=>"https://www.indeed.com/q-$40,000-l-Cocoa-West,-FL-jobs.html"},
    {:name=>"Lecanto", :url=>"https://www.indeed.com/q-$40,000-l-Lecanto,-FL-jobs.html"},
    {:name=>"Kathleen", :url=>"https://www.indeed.com/q-$40,000-l-Kathleen,-FL-jobs.html"},
    {:name=>"Heathrow", :url=>"https://www.indeed.com/q-$40,000-l-Heathrow,-FL-jobs.html"},
    {:name=>"South Gate Ridge", :url=>"https://www.indeed.com/q-$40,000-l-South-Gate-Ridge,-FL-jobs.html"},
    {:name=>"Combee Settlement", :url=>"https://www.indeed.com/q-$40,000-l-Combee-Settlement,-FL-jobs.html"},
    {:name=>"Davenport", :url=>"https://www.indeed.com/q-$40,000-l-Davenport,-FL-jobs.html"},
    {:name=>"Newberry", :url=>"https://www.indeed.com/q-$40,000-l-Newberry,-FL-jobs.html"},
    {:name=>"Lake Alfred", :url=>"https://www.indeed.com/q-$40,000-l-Lake-Alfred,-FL-jobs.html"},
    {:name=>"High Springs", :url=>"https://www.indeed.com/q-$40,000-l-High-Springs,-FL-jobs.html"},
    {:name=>"Fort Meade", :url=>"https://www.indeed.com/q-$40,000-l-Fort-Meade,-FL-jobs.html"},
    {:name=>"Pahokee", :url=>"https://www.indeed.com/q-$40,000-l-Pahokee,-FL-jobs.html"},
    {:name=>"Tequesta", :url=>"https://www.indeed.com/q-$40,000-l-Tequesta,-FL-jobs.html"},
    {:name=>"South Apopka", :url=>"https://www.indeed.com/q-$40,000-l-South-Apopka,-FL-jobs.html"},
    {:name=>"Sky Lake", :url=>"https://www.indeed.com/q-$40,000-l-Sky-Lake,-FL-jobs.html"},
    {:name=>"Inverness Highlands South", :url=>"https://www.indeed.com/q-$40,000-l-Inverness-Highlands-South,-FL-jobs.html"},
    {:name=>"Mascotte", :url=>"https://www.indeed.com/q-$40,000-l-Mascotte,-FL-jobs.html"},
    {:name=>"Pelican Bay", :url=>"https://www.indeed.com/q-$40,000-l-Pelican-Bay,-FL-jobs.html"},
    {:name=>"Bay Harbor Islands", :url=>"https://www.indeed.com/q-$40,000-l-Bay-Harbor-Islands,-FL-jobs.html"},
    {:name=>"St. Augustine South", :url=>"https://www.indeed.com/q-$40,000-l-St.-Augustine-South,-FL-jobs.html"},
    {:name=>"Ocean City", :url=>"https://www.indeed.com/q-$40,000-l-Ocean-City,-FL-jobs.html"},
    {:name=>"Mims", :url=>"https://www.indeed.com/q-$40,000-l-Mims,-FL-jobs.html"},
    {:name=>"Loughman", :url=>"https://www.indeed.com/q-$40,000-l-Loughman,-FL-jobs.html"},
    {:name=>"Fellsmere", :url=>"https://www.indeed.com/q-$40,000-l-Fellsmere,-FL-jobs.html"},
    {:name=>"Mount Plymouth", :url=>"https://www.indeed.com/q-$40,000-l-Mount-Plymouth,-FL-jobs.html"},
    {:name=>"Okeechobee", :url=>"https://www.indeed.com/q-$40,000-l-Okeechobee,-FL-jobs.html"},
    {:name=>"Surfside", :url=>"https://www.indeed.com/q-$40,000-l-Surfside,-FL-jobs.html"},
    {:name=>"Naples Park", :url=>"https://www.indeed.com/q-$40,000-l-Naples-Park,-FL-jobs.html"},
    {:name=>"Wahneta", :url=>"https://www.indeed.com/q-$40,000-l-Wahneta,-FL-jobs.html"},
    {:name=>"South Sarasota", :url=>"https://www.indeed.com/q-$40,000-l-South-Sarasota,-FL-jobs.html"},
    {:name=>"Valparaiso", :url=>"https://www.indeed.com/q-$40,000-l-Valparaiso,-FL-jobs.html"},
    {:name=>"Pine Manor", :url=>"https://www.indeed.com/q-$40,000-l-Pine-Manor,-FL-jobs.html"},
    {:name=>"Starke", :url=>"https://www.indeed.com/q-$40,000-l-Starke,-FL-jobs.html"},
    {:name=>"Tice", :url=>"https://www.indeed.com/q-$40,000-l-Tice,-FL-jobs.html"},
    {:name=>"South Highpoint", :url=>"https://www.indeed.com/q-$40,000-l-South-Highpoint,-FL-jobs.html"},
    {:name=>"Floral City", :url=>"https://www.indeed.com/q-$40,000-l-Floral-City,-FL-jobs.html"},
    {:name=>"Siesta Key", :url=>"https://www.indeed.com/q-$40,000-l-Siesta-Key,-FL-jobs.html"},
    {:name=>"Palm Springs North", :url=>"https://www.indeed.com/q-$40,000-l-Palm-Springs-North,-FL-jobs.html"},
    {:name=>"LaBelle", :url=>"https://www.indeed.com/q-$40,000-l-LaBelle,-FL-jobs.html"},
    {:name=>"River Ridge", :url=>"https://www.indeed.com/q-$40,000-l-River-Ridge,-FL-jobs.html"},
    {:name=>"Dundee", :url=>"https://www.indeed.com/q-$40,000-l-Dundee,-FL-jobs.html"},
    {:name=>"Hutchinson Island South", :url=>"https://www.indeed.com/q-$40,000-l-Hutchinson-Island-South,-FL-jobs.html"},
    {:name=>"Port LaBelle", :url=>"https://www.indeed.com/q-$40,000-l-Port-LaBelle,-FL-jobs.html"},
    {:name=>"Timber Pines", :url=>"https://www.indeed.com/q-$40,000-l-Timber-Pines,-FL-jobs.html"},
    {:name=>"Rio Pinar", :url=>"https://www.indeed.com/q-$40,000-l-Rio-Pinar,-FL-jobs.html"},
    {:name=>"Flagler Beach", :url=>"https://www.indeed.com/q-$40,000-l-Flagler-Beach,-FL-jobs.html"},
    {:name=>"Belleview", :url=>"https://www.indeed.com/q-$40,000-l-Belleview,-FL-jobs.html"},
    {:name=>"Zephyrhills West", :url=>"https://www.indeed.com/q-$40,000-l-Zephyrhills-West,-FL-jobs.html"},
    {:name=>"South Bay", :url=>"https://www.indeed.com/q-$40,000-l-South-Bay,-FL-jobs.html"},
    {:name=>"South Pasadena", :url=>"https://www.indeed.com/q-$40,000-l-South-Pasadena,-FL-jobs.html"},
    {:name=>"Samsula-Spruce Creek", :url=>"https://www.indeed.com/q-$40,000-l-Samsula-Spruce-Creek,-FL-jobs.html"},
    {:name=>"Kenneth City", :url=>"https://www.indeed.com/q-$40,000-l-Kenneth-City,-FL-jobs.html"},
    {:name=>"Plantation", :url=>"https://www.indeed.com/q-$40,000-l-Plantation,-FL-jobs.html"},
    {:name=>"Whiskey Creek", :url=>"https://www.indeed.com/q-$40,000-l-Whiskey-Creek,-FL-jobs.html"},
    {:name=>"Connerton", :url=>"https://www.indeed.com/q-$40,000-l-Connerton,-FL-jobs.html"},
    {:name=>"Big Pine Key", :url=>"https://www.indeed.com/q-$40,000-l-Big-Pine-Key,-FL-jobs.html"},
    {:name=>"Warm Mineral Springs", :url=>"https://www.indeed.com/q-$40,000-l-Warm-Mineral-Springs,-FL-jobs.html"},
    {:name=>"Wauchula", :url=>"https://www.indeed.com/q-$40,000-l-Wauchula,-FL-jobs.html"},
    {:name=>"White City", :url=>"https://www.indeed.com/q-$40,000-l-White-City,-FL-jobs.html"},
    {:name=>"Vamo", :url=>"https://www.indeed.com/q-$40,000-l-Vamo,-FL-jobs.html"},
    {:name=>"Pea Ridge", :url=>"https://www.indeed.com/q-$40,000-l-Pea-Ridge,-FL-jobs.html"},
    {:name=>"Sawgrass", :url=>"https://www.indeed.com/q-$40,000-l-Sawgrass,-FL-jobs.html"},
    {:name=>"Bay Hill", :url=>"https://www.indeed.com/q-$40,000-l-Bay-Hill,-FL-jobs.html"},
    {:name=>"Zephyrhills South", :url=>"https://www.indeed.com/q-$40,000-l-Zephyrhills-South,-FL-jobs.html"},
    {:name=>"Kensington Park", :url=>"https://www.indeed.com/q-$40,000-l-Kensington-Park,-FL-jobs.html"},
    {:name=>"Crawfordville", :url=>"https://www.indeed.com/q-$40,000-l-Crawfordville,-FL-jobs.html"},
    {:name=>"Three Oaks", :url=>"https://www.indeed.com/q-$40,000-l-Three-Oaks,-FL-jobs.html"},
    {:name=>"Daytona Beach Shores", :url=>"https://www.indeed.com/q-$40,000-l-Daytona-Beach-Shores,-FL-jobs.html"},
    {:name=>"Samoset", :url=>"https://www.indeed.com/q-$40,000-l-Samoset,-FL-jobs.html"},
    {:name=>"Ridge Manor", :url=>"https://www.indeed.com/q-$40,000-l-Ridge-Manor,-FL-jobs.html"},
    {:name=>"Butler Beach", :url=>"https://www.indeed.com/q-$40,000-l-Butler-Beach,-FL-jobs.html"},
    {:name=>"Lake Sarasota", :url=>"https://www.indeed.com/q-$40,000-l-Lake-Sarasota,-FL-jobs.html"},
    {:name=>"Balm", :url=>"https://www.indeed.com/q-$40,000-l-Balm,-FL-jobs.html"},
    {:name=>"Cortez", :url=>"https://www.indeed.com/q-$40,000-l-Cortez,-FL-jobs.html"},
    {:name=>"Parker", :url=>"https://www.indeed.com/q-$40,000-l-Parker,-FL-jobs.html"},
    {:name=>"The Meadows", :url=>"https://www.indeed.com/q-$40,000-l-The-Meadows,-FL-jobs.html"},
    {:name=>"Lochmoor Waterway Estates", :url=>"https://www.indeed.com/q-$40,000-l-Lochmoor-Waterway-Estates,-FL-jobs.html"},
    {:name=>"West DeLand", :url=>"https://www.indeed.com/q-$40,000-l-West-DeLand,-FL-jobs.html"},
    {:name=>"Stock Island", :url=>"https://www.indeed.com/q-$40,000-l-Stock-Island,-FL-jobs.html"},
    {:name=>"Lake Belvedere Estates", :url=>"https://www.indeed.com/q-$40,000-l-Lake-Belvedere-Estates,-FL-jobs.html"},
    {:name=>"Mary Esther", :url=>"https://www.indeed.com/q-$40,000-l-Mary-Esther,-FL-jobs.html"},
    {:name=>"Nassau Village-Ratliff", :url=>"https://www.indeed.com/q-$40,000-l-Nassau-Village-Ratliff,-FL-jobs.html"},
    {:name=>"Brookridge", :url=>"https://www.indeed.com/q-$40,000-l-Brookridge,-FL-jobs.html"},
    {:name=>"Grant-Valkaria", :url=>"https://www.indeed.com/q-$40,000-l-Grant-Valkaria,-FL-jobs.html"},
    {:name=>"Belleair", :url=>"https://www.indeed.com/q-$40,000-l-Belleair,-FL-jobs.html"},
    {:name=>"June Park", :url=>"https://www.indeed.com/q-$40,000-l-June-Park,-FL-jobs.html"},
    {:name=>"Holmes Beach", :url=>"https://www.indeed.com/q-$40,000-l-Holmes-Beach,-FL-jobs.html"},
]
